name: Bump version

on: 
  push:
    branches: master
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master

    - name: Configure repo
      run: |
        git config --local user.email "weide-zhou@outlook.com"
        git config --local user.name "weide-zhou"
        git pull origin master --tags
        git tag v0.20.06
        git push --tags


#    - name: Push changes
#      uses: Woile/github-push-action@master
#      with:
#        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#        tags: "true"
